// <auto-generated />
using GeziYazisiSitesi.Concrete.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GeziYazisiSitesi.Migrations
{
    [DbContext(typeof(GeziContext))]
    [Migration("20190118083554_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeziYazisiSitesi.Modals.Sehir", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<int>("UlkeId");

                    b.HasKey("SehirId");

                    b.HasIndex("UlkeId");

                    b.ToTable("Sehirs");
                });

            modelBuilder.Entity("GeziYazisiSitesi.Modals.Ulke", b =>
                {
                    b.Property<int>("UlkeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.HasKey("UlkeId");

                    b.ToTable("Ulkes");
                });

            modelBuilder.Entity("GeziYazisiSitesi.Modals.Uye", b =>
                {
                    b.Property<int>("UyeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.HasKey("UyeID");

                    b.ToTable("Uyes");
                });

            modelBuilder.Entity("GeziYazisiSitesi.Modals.Yazi", b =>
                {
                    b.Property<int>("YaziId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Baslik")
                        .IsRequired();

                    b.Property<int>("BegenmeSayisi");

                    b.Property<int>("Goruntulenme");

                    b.Property<string>("Icerik")
                        .IsRequired();

                    b.Property<bool>("Onay");

                    b.Property<string>("Resim")
                        .IsRequired();

                    b.Property<int>("SehirId");

                    b.Property<DateTime>("Tarih");

                    b.Property<int>("UyeId");

                    b.Property<int>("YorumSayisi");

                    b.HasKey("YaziId");

                    b.HasIndex("SehirId");

                    b.HasIndex("UyeId");

                    b.ToTable("Yazis");
                });

            modelBuilder.Entity("GeziYazisiSitesi.Modals.Sehir", b =>
                {
                    b.HasOne("GeziYazisiSitesi.Modals.Ulke", "Ulke")
                        .WithMany()
                        .HasForeignKey("UlkeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeziYazisiSitesi.Modals.Yazi", b =>
                {
                    b.HasOne("GeziYazisiSitesi.Modals.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeziYazisiSitesi.Modals.Uye", "Uye")
                        .WithMany("Yazilar")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
