// <auto-generated />
using GeziYazisiSitesi.Concrete.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GeziYazisiSitesi.Migrations
{
    [DbContext(typeof(GeziContext))]
    partial class GeziContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeziYazisiSitesi.Modals.Uye", b =>
                {
                    b.Property<int>("UyeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.HasKey("UyeID");

                    b.ToTable("Uyes");
                });

            modelBuilder.Entity("GeziYazisiSitesi.Modals.Yazi", b =>
                {
                    b.Property<int>("YaziId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("YazarUyeID");

                    b.Property<string>("baslik");

                    b.HasKey("YaziId");

                    b.HasIndex("YazarUyeID");

                    b.ToTable("Yazis");
                });

            modelBuilder.Entity("GeziYazisiSitesi.Modals.Yazi", b =>
                {
                    b.HasOne("GeziYazisiSitesi.Modals.Uye", "Yazar")
                        .WithMany("Yazilar")
                        .HasForeignKey("YazarUyeID");
                });
#pragma warning restore 612, 618
        }
    }
}
